name = "DeltaSugar"
uuid = "aa57e966-2371-4a63-bded-4a6ccd8a1b12"
authors = ["Casey Kneale"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
